# docker-compose -f docker-compose.production.yml up -d
version: "2.3"
services:
  nginx:
    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:${CI_COMMIT_REF_SLUG}_nginx.$CI_PIPELINE_ID #finish image from registry
    ports:
      - "80:80"
    # volumes:
    #   - ./www:/var/www
    depends_on:
      php:
        condition: service_healthy #check 
    environment:
      - ENV=production
  php:
    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:${CI_COMMIT_REF_SLUG}_php.$CI_PIPELINE_ID #finish image from registry
    # volumes:
    #   - ./www:/var/www
    healthcheck:
      test: ["CMD", "php-fpm", "-t"] 
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 1s