# docker-compose up -d
# curl -H "Host: docker.marsel.host" http://localhost:80
# curl -H "Host: docker.marsel.host" http://localhost:80/phpinfo
version: "2.3"
services:
  nginx:
    build: ./nginx
    image: compose_nginx #name create image
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www #nginx handler
    depends_on:
      php:
        condition: service_healthy #check 
    environment:
      - ENV=development
  php:
    build: ./php
    image: compose_php #name create image
    volumes:
      - ./www:/var/www #php handler
    healthcheck:
      test: ["CMD", "php-fpm", "-t"] 
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 1s