---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-claim
spec:
  accessModes:
    - ReadWriteOnce #1 pod может читать и записывать данные
  resources:
    requests:
      storage: 1Gi