---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-2
spec:
  replicas: 6
  selector:
    matchLabels:
      app: my-app-2
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: my-app-2
    spec:
      containers:
        - image: nginx:1.14
          name: nginx
          ports:
            - containerPort: 80