---
apiVersion: v1
kind: Secret
meatadata:
  name: csi-cephfs-secret
  namespace: ceph-csi-cephfs
stringData:
  # Required for dynamically provisioned volumes
  adminID: fs
  adminKey: <Ceph auth key correspondind to ID above>