apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-web-deployment-autoscaling
  labels:
    app: my-k8s-deployment
spec:
  # replicas: 3 # autoscaling from us
  selector:
    matchLabels:
      project: xyz
  template:
    metadata:
      labels:
        project: xyz # service will look for these PODS labels
    spec:
      containers:
        - name: xyz-web
          image: adv4000/k8sphp:latest
          ports:
            - containerPort: 80 # port on prod
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-web-deployment-autoscaling
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-autoscaling-pod-service
  labels: 
    env: prod
    owner: AntonShumeyko
spec:
  selector:
    project: xyz
  ports:
    - name: app-listener
      protocol: TCP
      port: 80 #port on load listener
      targetPort: 80 #port on pod
  type: LoadBalancer
