# docker-compose -f docker-compose.yml -f docker-compose.test.yml up --abort-on-container-exit --exit-code-from test запуск тестов
# docker-compose -f docker-compose.production.yml -f docker-compose.test.yml up --abort-on-container-exit --exit-code-from test 
version: "2.3"
services:
  test:
    build: ./test
    depends_on:
      - php
      - nginx